name: CI-release

on:
  # Release event https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release
  # Note: The `prereleased` type will not trigger for pre-releases published from draft releases, but the `published`
  # type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to `published`
  # instead of `released` and `prereleased`.
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing tag to release (e.g., v0.1.0)'
        required: true
      dry-run:
        description: Dry-run
        required: false
        default: true
        type: boolean

run-name: >- 
  ${{ 
    github.event_name == 'workflow_dispatch' && format(
      '{0}: {1} {2}',
      github.workflow,
      inputs.tag,
      fromJSON('["", " (dry-run)"]')[inputs.dry-run]
    ) || '' 
  }}

# Ensure that only a single release automation workflow can run at a time.
concurrency: Release automation

# Environment variables
# https://docs.github.com/en/actions/learn-github-actions/variables

jobs:
  release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check semver version in tag
        run: |
          prefix="v"
          tag_name="${{ github.event.inputs.tag || github.event.release.tag_name }}"
          semver_regex="(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(([a-z-][0-9a-z-]+|[0-9a-z-]+[a-z-][0-9a-z-]*|0|[1-9][0-9]*)(\\.([a-z-][0-9a-z-]+|[0-9a-z-]+[a-z-][0-9a-z-]*|0|[1-9][0-9]*))*))?(\+([0-9a-z-]+(\.[0-9a-z-]+)*))?"
          echo "Checking version: $semver_regex"
          echo "$tag_name" | grep -Eq "^$prefix$semver_regex\$"
        shell: bash
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.tag || github.event.release.tag_name }}
          fetch-depth: 400
          fetch-tags: 'true'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Publish to Staging Repository
        if: success()
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_githubUser: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUB_TOKEN }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        # com.javiersc.semver.gradle.plugin should pick the actual tag
        run: ./gradlew publish -Ppublish.central=${{ inputs.dry-run && 'false' || 'true' }} --stacktrace

# Don't forget to deploy the release to central
# * 'Close' the repo to trigger the evaluations of to components against the requirements
# * 'Release' the repo
# https://central.sonatype.org/publish/release/
# If any errors occur, check the FAQ
# https://central.sonatype.org/faq/400-error/